a=int(input("Enter the first no:"))
b=int(input("Enter the Second no:"))
print("Sum is:",(a+b))
print("Sub is:",(a-b))
print("Mul is:",(a*b))
print("Div is:",(a/b))
print("FloorDiv is:",(a//b))
print("Mod is:",(a%b))
print("Power is:",(a**b))